apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-umbrella.fullname" . }}
  {{- if .Values.service.annotations }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{ include "api-umbrella.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "api-umbrella.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}